<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2vustcu\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2vustcu/appProdProjectContainer.php') {
    touch(__DIR__.'/Container2vustcu.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container2vustcu\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container2vustcu\appProdProjectContainer([
    'container.build_hash' => '2vustcu',
    'container.build_id' => '72eaf235',
    'container.build_time' => 1585393444,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2vustcu');
